/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.Estudiante;
import clases.Participante;
import clases.Reserva;
import clases.Sala;
import com.github.lgooddatepicker.components.TimePickerSettings;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import primerproyectoprogramado.AplSystem;
import utilidades.EmailValidator;
import utilidades.sendSMS;
import utilidades.Correo;

/**
 *
 * @author Angelo PC
 */
public class VentanaCrearReserva extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCrearCita
     */
    public VentanaCrearReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DatePickerSettings dateSettings = new com.github.lgooddatepicker.components.DatePickerSettings();
        TimePickerSettings timeSettings = new com.github.lgooddatepicker.components.TimePickerSettings();
        dateSettings.setAllowEmptyDates(false);
        timeSettings.setAllowEmptyTimes(false);
        timeSettings.setInitialTimeToNow();
        dateTimePicker2 = new com.github.lgooddatepicker.components.DateTimePicker(dateSettings, timeSettings);
        TimePickerSettings tset1 = new com.github.lgooddatepicker.components.TimePickerSettings();
        tset1.setAllowEmptyTimes(false);
        tset1.setInitialTimeToNow();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker(tset1);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        Estudiante eTemp = AplSystem.getSesionActiva();
        jLabel12.setText("Encargado: "+ eTemp.getNombre());
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha y Hora de Inicio:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        dateTimePicker2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dateTimePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        timePicker1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(timePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        jLabel2.setText("Hora de Fin:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabel3.setText("Capacidad Requerida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 30, -1));

        jLabel5.setText("Participantes:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 300, -1));

        jButton2.setText("+");
        jButton2.setBackground(new java.awt.Color(21, 14, 56));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 50, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 310, 80));

        jButton1.setText("Buscar Salas Disponibles");
        jButton1.setBackground(new java.awt.Color(21, 14, 56));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 210, 80));

        jLabel6.setText("Recursos de la sala:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jButton3.setText("+");
        jButton3.setBackground(new java.awt.Color(21, 14, 56));
        jButton3.setEnabled(false);
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 50, 70));

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 310, 80));

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 260, 30));

        jLabel7.setText("Asunto por tratar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 260, 30));

        jLabel4.setText("Correo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jLabel9.setText("Salas disponibles:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_interfaz/AcceptBtn.png"))); // NOI18N
        jButton4.setText("Confirmar Reserva");
        jButton4.setActionCommand("Accept");
        jButton4.setBackground(new java.awt.Color(21, 14, 56));
        jButton4.setEnabled(false);
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 190, 40));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_interfaz/BackBtn.png"))); // NOI18N
        jButton5.setText("Volver");
        jButton5.setBackground(new java.awt.Color(21, 14, 56));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 100, 30));

        jComboBox1.setEnabled(false);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 100, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizarra", "Ventana", "Proyector", "Ventilador", "Toma Corriente", "Auditorio", "Computador" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 260, -1));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, -1, -1));
        jLabel12.getAccessibleContext().setAccessibleName("Coordinador:");

        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 190, -1));
        jProgressBar1.setVisible(false);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_interfaz/Reserva.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jComboBox3.getSelectedItem() != null){
            if(jTextArea1.getText().length() > 0){
                jTextArea1.setText(jTextArea1.getText() +"\n" + (String) jComboBox3.getSelectedItem());
            }
            else{
                jTextArea1.setText((String) jComboBox3.getSelectedItem());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String correo = jTextField5.getText();
        String nombre = jTextField6.getText();
        EmailValidator validator = new EmailValidator();
            if(jTextArea2.getText().contains(correo)){
                JOptionPane.showMessageDialog(this, "Ya se ha añadido este "
                        + "correo de participantes");
                return;
            }
            if(validator.validate(correo)){
                if(nombre.contains(" ") && nombre.length() > 2){
                    if(contador<capacidad_requerida){
                    participantes.add(new Participante(nombre, correo));
                    contador += 1;
                    if(jTextArea2.getText().length() > 0){
                        jTextArea2.setText(jTextArea2.getText() +"\n" + "Nombre: "
                        + nombre + " | Correo: " + correo);
                        }
                    else{
                        jTextArea2.setText("Nombre: "
                        + nombre + " | Correo: " + correo);
                        }
                    jTextField5.setText("");
                    jTextField6.setText("");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Ha alcanzado "
                                + "el máximo de integrantes específicado");
                    }
                }else{
                
                JOptionPane.showMessageDialog(this, "Inserte por lo "
                                 + "menos un nombre y un apellido");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "El correo electrónico "
                    +correo+ " es invalido");        
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new VentanaEstudiante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed
    /**
     * Method that occurs when the "Search for rooms" button is pressed
     * it enables the rest of the interface in which the user writes the
     * information relevant to the reserve
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jComboBox1.removeAllItems();
        jComboBox1.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jTextArea2.setEnabled(true);
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextArea2.setText("");
        participantes = new ArrayList<>();
        contador = 1;
        String recursos_seleccionados = jTextArea1.getText();
        ArrayList<String> recursos;
        dateAndTime = dateTimePicker2.getDateTimeStrict();
        time = timePicker1.getTime();
        String capacidad = jTextField1.getText();
        if(!(capacidad.chars().allMatch(Character::isDigit) && capacidad.length()>0 && capacidad.length()<3 && capacidad.charAt(0) != '0')){
            JOptionPane.showMessageDialog(this, "La capacidad debe ser un entero entre 3 y 99");
            return;
        }
        if((int) Integer.parseInt(capacidad) < 3){
            JOptionPane.showMessageDialog(this, "La capacidad minima de participantes es de 3");
            return;
        }
        else{
            capacidad_requerida = (int) Integer.parseInt(capacidad);
        }
        if(!"".equals(recursos_seleccionados)){
            recursos = new ArrayList<>(Arrays.asList(recursos_seleccionados.split("\n")));
        }
        else{
            recursos = new ArrayList<>();
        }
        if(dateAndTime.toLocalTime().isAfter(time) || dateAndTime.toLocalTime().equals(time)){
            JOptionPane.showMessageDialog(this, "La hora de inicio tiene que "
                    + "ser menor a la hora final");
            return;
        }
        if((dateAndTime.toLocalTime().isBefore(LocalTime.now()) || dateAndTime.toLocalTime().equals(LocalTime.now())) && dateAndTime.equals(LocalDateTime.now())){
            JOptionPane.showMessageDialog(this, "La reserva debe hacerse con"
                    + " 30 minutos de antelación");
            return;
        }
        LocalDateTime ahora = LocalDateTime.now();
        LocalDateTime inAWeek = ahora.plusWeeks(1);
        if(dateAndTime.isAfter(inAWeek)){
            JOptionPane.showMessageDialog(this, "Solo se pueden hacer reservas"
                    + " en un rango de una semana");
            return;
        }
        if(dateAndTime.isBefore(ahora)){
            JOptionPane.showMessageDialog(this, "No se pueden hacer reservas"
                    + " en el pasado");
            return;
        }
        ArrayList<Sala> salas_disponibles = AplSystem.BuscarSalas(dateAndTime, time, recursos, capacidad_requerida);
        if(salas_disponibles.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay salas disponibles"
                    + " que cumplan con sus requisitos por favor"
                    + " modifique los requisitos e intente nuevamente.");
        }
        else{
            for(Sala sala: salas_disponibles){
                jComboBox1.addItem(sala.getId());
            }
            jComboBox1.setEnabled(true);
            jTextField3.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jTextArea2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Method which verifies that the minimum amount of participants
     * has been added and that a topic has been added to the meeting
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(contador > 2){
            if(jTextField3.getText().length() > 1){
                jProgressBar1.setVisible(true);
                jProgressBar1.setStringPainted(true);
                jProgressBar1.setValue(0);
                new Thread() {
        public void run() {
            crearReserva();
        }
        }.start();
                
        }
            else{
            JOptionPane.showMessageDialog(this, "Se debe insertar el asunto por tratar");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La cantidad minima de participantes"
                    + " adicionales es de dos");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void crearReserva(){
        this.setEnabled(false);
        String seleccionada = (String) jComboBox1.getSelectedItem();
        Sala sala = AplSystem.getSala((String)jComboBox1.getSelectedItem());
        Estudiante estudiante = AplSystem.getSesionActiva();
        int anio = dateAndTime.getYear();
        int mes = dateAndTime.getMonthValue();
        int dia = dateAndTime.getDayOfMonth();
        int horaInicio = dateAndTime.toLocalTime().getHour();
        int minInicio = dateAndTime.toLocalTime().getMinute();
        int horaFin = time.getHour();
        int minFin = time.getMinute();
        Reserva reserva;
        reserva = new Reserva(sala,estudiante,anio,mes,dia,horaInicio,minInicio,horaFin,minFin);
        reserva.setCodigo(sala.getId()+reserva.getId()+estudiante.getCarne());
        AplSystem.agregarReserva(reserva);
        sala.agregarReserva();
        estudiante.agregarReserva();
        sendSMS sms=new sendSMS("Su código de calificación de reserva es: " + reserva.getCodigo(),estudiante.getNumero());
        sms.sendSms();
        String emisor="edjiron@gmail.com";
        String contraseña="jqalrtwrjxnkhpic";
        ArrayList<String> receptores=new ArrayList<>();
        for(Participante i:participantes){
            receptores.add(i.getCorreo());
            reserva.addParticipante(i);
        }
        jProgressBar1.setValue(25);
        String asunto=jTextField3.getText();
        String texto="El estudiante "+estudiante.getNombre()+" lo ha invitado para "+asunto+" en la sala "
                +sala.getId()+ " ubicada en "+sala.getUbicacion()+". La reunión empieza "+reserva.getInicio().toString()+
                        " y concluye "+reserva.getFin().toString()+".";
        Correo correo=new Correo(emisor,contraseña,receptores,asunto,texto);
        try {
            jProgressBar1.setValue(50);
            correo.sendCorreo();
        } catch (MessagingException ex) {
            Logger.getLogger(VentanaCrearReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
        jProgressBar1.setValue(100);
        AplSystem.guardarXML(AplSystem.getEstudiantes(), "estudiantesDB");
        AplSystem.guardarXML(AplSystem.getSalas(), "salasDB");
        AplSystem.guardarXML(AplSystem.getReservas(), "reservasDB");
        this.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Operación exitosa");
        jComboBox1.removeAllItems();
        jComboBox1.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jTextArea2.setEnabled(true);
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextArea2.setText("");
        jTextArea1.setText("");
        participantes = new ArrayList<>();
        contador = 1;
        jProgressBar1.setValue(0);
        jProgressBar1.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearReserva().setVisible(true);
            }
        });
    }
    private ArrayList<Participante> participantes = new ArrayList<>();
    private int contador = 1;
    private int capacidad_requerida;
    LocalDateTime dateAndTime;
    LocalTime time;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
