/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Sala;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import primerproyectoprogramado.AplSystem;

/**
 *
 * @author Angelo PC
 */
public class VentanaAgregarSala extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregarSala
     */
    public VentanaAgregarSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        ArrayList<String> horarios = AplSystem.getIDHorarios();
        for (Iterator<String> it = horarios.iterator(); it.hasNext();) {
            String horario = it.next();
            jComboBox2.addItem(horario);
        }
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Horarios:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel5.setText("Recursos de la sala:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 120, -1));

        jLabel3.setText("Identificador de la sala:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setText("Capacidad Máxima Sala:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 30, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 300, 80));

        jLabel4.setText("Ubicación:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 300, -1));

        jButton1.setBackground(new java.awt.Color(21, 14, 56));
        jButton1.setForeground(new java.awt.Color(21, 14, 56));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_interfaz/AcceptBtn.png"))); // NOI18N
        jButton1.setActionCommand("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 40, 40));

        jButton5.setBackground(new java.awt.Color(21, 14, 56));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_interfaz/BackBtn.png"))); // NOI18N
        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 100, 30));

        jButton2.setBackground(new java.awt.Color(21, 14, 56));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 50, 30));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 250, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 300, 80));

        jButton3.setBackground(new java.awt.Color(21, 14, 56));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 50, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizarra", "Ventana", "Proyector", "Ventilador", "Toma Corriente", "Auditorio", "Computador" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_interfaz/AgregarSala.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new VentanaAdministrador().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    /**
     * Method that happens when an add button is pressed, 
     * the element selected in the comboBox is sent to the TextArea if it
     * has not been selected already
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jComboBox2.getSelectedItem() != null){
            if(!(jTextArea1.getText().contains((String)jComboBox2.getSelectedItem())))
            {
                if(jTextArea1.getText().length() > 0){
                    jTextArea1.setText(jTextArea1.getText() +"\n" + (String) jComboBox2.getSelectedItem());
                }
                else{
                    jTextArea1.setText((String) jComboBox2.getSelectedItem());
                }
            }
            else{
            JOptionPane.showMessageDialog(this, "El horario, " +
                   (String)jComboBox2.getSelectedItem()+ " ya fue seleccionado"
                           + " por favor intente con otro" );
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Event which validates the Sala entry fields, if the events are correct,
     * then the sala is created.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String identificador = jTextField2.getText();
        String capacidad = jTextField1.getText();
        String ubicacion = jTextField4.getText();
        String recursos_seleccionados = jTextArea2.getText();
        String horarios_seleccionados = jTextArea1.getText();
        ArrayList<String> recursos;
        ArrayList<String> horarios;
        if(!"".equals(horarios_seleccionados)){
            horarios = new ArrayList<>(Arrays.asList(horarios_seleccionados.split("\n")));
        }
        else{
            horarios = new ArrayList<>();
        }
        if(!"".equals(recursos_seleccionados)){
            recursos = new ArrayList<>(Arrays.asList(recursos_seleccionados.split("\n")));
        }
        else{
            recursos = new ArrayList<>();
        }
        String[] identificador_partes = identificador.split("-");
        if(identificador_partes.length < 2){
            JOptionPane.showMessageDialog(this, "El identificador de sala debe tener"
                    + " el formato 'SAL-000'");
            return;
        }
        identificador = identificador_partes[0].toUpperCase() + "-" + identificador_partes[1];
        if(identificador_partes[0].length() == 3 && identificador_partes[1].length() == 3 && identificador_partes[1].chars().allMatch( Character::isDigit )){
            if(capacidad.chars().allMatch( Character::isDigit) && capacidad.length()>0 && capacidad.length()<3 && capacidad.charAt(0) != '0'){
                if(ubicacion.length() > 0){
                    if(!(horarios.isEmpty())){
                        Sala s = new Sala(identificador, ubicacion,(int)Integer.parseInt(capacidad), recursos, true, 0, AplSystem.getHorariosByID(horarios));
                        if(AplSystem.añadirSala(s)){
                        JOptionPane.showMessageDialog(this, "Operacion"
                                 + " exitosa");
                        AplSystem.guardarXML(AplSystem.getSalas(), "salasDB");
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jTextField4.setText("");
                        jTextArea1.setText("");
                        jTextArea2.setText("");
                        jComboBox2.setSelectedIndex(0);
                        jComboBox3.setSelectedIndex(0);
                        }else{JOptionPane.showMessageDialog(this, "El identificador "
                                + identificador + " ya está registrado en el sistema");
                }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Por favor seleccione por lo menos un horario");
                    }
                }
                else
                    JOptionPane.showMessageDialog(this,"Por favor inserte una ubicación");
            }
            else{
                JOptionPane.showMessageDialog(this, "La capacidad debe ser un entero entre 1 y 99");
            }
        }
        else{
        JOptionPane.showMessageDialog(this, "El identificador de sala debe tener"
                    + " el formato 'SAL-000'");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    /**
     * Method that happens when an add button is pressed, 
     * the element selected in the comboBox is sent to the TextArea
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jComboBox3.getSelectedItem() != null){
            if(jTextArea2.getText().length() > 0){
                jTextArea2.setText(jTextArea2.getText() +"\n" + (String) jComboBox3.getSelectedItem());
            }
            else{
                jTextArea2.setText((String) jComboBox3.getSelectedItem());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
